- name: "Create config directory"
  file:
    path: "{{ user_home }}/{{ item.path }}"
    state: directory
  loop:
    - { path: ".config/" }

- name: "Deploy wezterm.lua"
  file:
    src: "{{ dotfiles_home }}/roles/wezterm/files/"
    dest: "{{ user_home }}/.config/wezterm"
    state: "link"
    force: yes
