- name: "Deploy awesome configs"
  file:
    src: "{{ dotfiles_home }}/roles/wm/files/awesome/"
    dest: "{{ user_home }}/.config/awesome"
    state: "link"
    force: yes

- name: "Deploy i3 configs"
  file:
    src: "{{ dotfiles_home }}/roles/wm/files/i3/"
    dest: "{{ user_home }}/.config/i3"
    state: "link"
    force: yes

- name: "Deploy Xresources"
  file:
    src: "{{ dotfiles_home }}/roles/wm/files/Xresources"
    dest: "{{ user_home }}/.Xresources"
    state: "link"
    force: yes

- name: "Deploy polybar configs"
  file:
    src: "{{ dotfiles_home }}/roles/wm/files/polybar/"
    dest: "{{ user_home }}/.config/polybar"
    state: "link"
    force: yes

- name: "Deploy picom configs"
  file:
    src: "{{ dotfiles_home }}/roles/wm/files/picom.conf"
    dest: "{{ user_home }}/.config/picom.conf"
    state: "link"
    force: yes


